### ISSUE TITLE
No popup on map for searchresult

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/lmsearch-plugin#10]
When showing the searchresult on the map there is a popup which can block a large portion of the geometry and when popup is closed the geometry disappears. The popup isn't needed, since it tells the name of the estate and that is already known from search that estate.
Current:
![image](https://user-images.githubusercontent.com/48793206/100765476-d0ec0700-33f7-11eb-963f-ece751e9c406.png)
New:
![image](https://user-images.githubusercontent.com/48793206/100765941-6091b580-33f8-11eb-85ab-33fd273ac26b.png)

The style should also be configurable.

**Comment by tonnyandersson** [comment]
Instead of removing the popup entirely, here are some suggestions:

- Add an option to allow popup/sidebar/infowindow to be closed without deselecting the feature, like _deselectOnClose: false_
- Make the popup movable

Also, and please correct me if I'm wrong here, but isn't the style already configurable via selectionStyles in featureinfoOptions?
